version: "3.7"

services:
  web:
    container_name: react_app
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - ./src:/app/src
    ports:
      - "80:80"
    command: >
      sh -c "yarn build && serve -s build"
    environment:
      NODE_ENV: production

volumes:
  nginx_secrets: