version: "3"

services:
  nginx-react:
    image: techassignment-ethan:latest
    container_name: techassignment-ethan
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
    ports:
      - "80:80"
    env_file:
      - .env